import { TranslationLabels } from "./types";

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'fr', name: 'Français' },
  { code: 'de', name: 'Deutsch' },
  { code: 'it', name: 'Italiano' },
  { code: 'pt', name: 'Português' },
  { code: 'zh', name: '中文' },
  { code: 'ja', name: '日本語' },
];

export const FONTS = [
  { id: 'standard', translationKey: 'fontStandard', sans: 'Outfit', serif: 'Playfair Display' },
  { id: 'modern', translationKey: 'fontModern', sans: 'Inter', serif: 'Inter' },
  { id: 'classic', translationKey: 'fontClassic', sans: 'Inter', serif: 'Lora' },
  { id: 'editorial', translationKey: 'fontEditorial', sans: 'Merriweather', serif: 'Playfair Display' },
];

export const TRANSLATIONS: Record<string, TranslationLabels> = {
  en: {
    heroTitle: "Discover Your Next",
    heroSubtitle: "Your intelligent guide to history, routes, hidden spots, and culinary delights.",
    fromPlaceholder: "From (Origin)",
    toPlaceholder: "To (Destination)",
    exploreButton: "Explore",
    locating: "Locating...",
    tabOverview: "Overview",
    tabJourney: "Journey",
    tabHotels: "Stays",
    tabMap: "Map",
    tabAttractions: "Attractions",
    tabFood: "Dining",
    overviewHeader: "Overview",
    bestTime: "Best Time to Visit",
    currency: "Currency",
    historyHeader: "Historical Snapshot",
    routesHeader: "Travel Options",
    from: "From",
    viewMap: "View Route Map",
    travelTipTitle: "Travel Tip",
    travelTipText: "Prices and durations are estimates. Always check real-time availability.",
    hotelsHeader: "Where to Stay",
    bookRoom: "Check Availability",
    budgetStays: "Budget & Value",
    luxuryStays: "Premium & Luxury",
    priceFilterLabel: "Max Price / Night",
    mapHeader: "Interactive Map",
    mapSubtext: "Explore the route, attractions, and photography spots.",
    attractionsHeader: "Must-Visit Spots",
    allAttractions: "All Attractions",
    cameraSpots: "Camera Spots",
    proTip: "Pro Tip",
    cuisineHeader: "Local Cuisine",
    tryAt: "Try at",
    tipsHeader: "Essential Travel Tips",
    settingsHeader: "Settings",
    languageLabel: "Language",
    typographyLabel: "Typography",
    fontStandard: "Standard",
    fontModern: "Modern",
    fontClassic: "Classic",
    fontEditorial: "Editorial"
  },
  es: {
    heroTitle: "Descubre tu Próxima",
    heroSubtitle: "Tu guía inteligente de historia, rutas, lugares ocultos y delicias culinarias.",
    fromPlaceholder: "Desde (Origen)",
    toPlaceholder: "A (Destino)",
    exploreButton: "Explorar",
    locating: "Localizando...",
    tabOverview: "Resumen",
    tabJourney: "Viaje",
    tabHotels: "Alojamiento",
    tabMap: "Mapa",
    tabAttractions: "Atracciones",
    tabFood: "Comida",
    overviewHeader: "Resumen",
    bestTime: "Mejor época para visitar",
    currency: "Moneda",
    historyHeader: "Resumen Histórico",
    routesHeader: "Opciones de Viaje",
    from: "Desde",
    viewMap: "Ver Mapa de Ruta",
    travelTipTitle: "Consejo de Viaje",
    travelTipText: "Los precios y duraciones son estimados. Verifique siempre la disponibilidad real.",
    hotelsHeader: "Dónde Alojarse",
    bookRoom: "Ver Disponibilidad",
    budgetStays: "Económico y Valor",
    luxuryStays: "Premium y Lujo",
    priceFilterLabel: "Precio Máx / Noche",
    mapHeader: "Mapa Interactivo",
    mapSubtext: "Explora la ruta, atracciones y puntos fotográficos.",
    attractionsHeader: "Lugares Imperdibles",
    allAttractions: "Todas las Atracciones",
    cameraSpots: "Puntos de Cámara",
    proTip: "Consejo Pro",
    cuisineHeader: "Cocina Local",
    tryAt: "Probar en",
    tipsHeader: "Consejos Esenciales",
    settingsHeader: "Configuración",
    languageLabel: "Idioma",
    typographyLabel: "Tipografía",
    fontStandard: "Estándar",
    fontModern: "Moderno",
    fontClassic: "Clásico",
    fontEditorial: "Editorial"
  },
  fr: {
    heroTitle: "Découvrez Votre Prochaine",
    heroSubtitle: "Votre guide intelligent pour l'histoire, les itinéraires, les lieux cachés et les délices culinaires.",
    fromPlaceholder: "De (Origine)",
    toPlaceholder: "À (Destination)",
    exploreButton: "Explorer",
    locating: "Localisation...",
    tabOverview: "Aperçu",
    tabJourney: "Voyage",
    tabHotels: "Hôtels",
    tabMap: "Carte",
    tabAttractions: "Attractions",
    tabFood: "Restauration",
    overviewHeader: "Aperçu",
    bestTime: "Meilleur moment pour visiter",
    currency: "Devise",
    historyHeader: "Aperçu Historique",
    routesHeader: "Options de Voyage",
    from: "De",
    viewMap: "Voir la Carte",
    travelTipTitle: "Conseil de Voyage",
    travelTipText: "Les prix et durées sont des estimations. Vérifiez toujours la disponibilité en temps réel.",
    hotelsHeader: "Où Séjourner",
    bookRoom: "Voir Disponibilité",
    budgetStays: "Budget & Valeur",
    luxuryStays: "Premium & Luxe",
    priceFilterLabel: "Prix Max / Nuit",
    mapHeader: "Carte Interactive",
    mapSubtext: "Explorez l'itinéraire, les attractions et les spots photo.",
    attractionsHeader: "Lieux Incontournables",
    allAttractions: "Toutes les Attractions",
    cameraSpots: "Spots Photo",
    proTip: "Conseil Pro",
    cuisineHeader: "Cuisine Locale",
    tryAt: "Essayer à",
    tipsHeader: "Conseils de Voyage Essentiels",
    settingsHeader: "Paramètres",
    languageLabel: "Langue",
    typographyLabel: "Typographie",
    fontStandard: "Standard",
    fontModern: "Moderne",
    fontClassic: "Classique",
    fontEditorial: "Éditorial"
  },
  de: {
    heroTitle: "Entdecken Sie Ihr Nächstes",
    heroSubtitle: "Ihr intelligenter Reiseführer für Geschichte, Routen, versteckte Orte und kulinarische Köstlichkeiten.",
    fromPlaceholder: "Von (Ursprung)",
    toPlaceholder: "Nach (Ziel)",
    exploreButton: "Erkunden",
    locating: "Standortbestimmung...",
    tabOverview: "Übersicht",
    tabJourney: "Reise",
    tabHotels: "Unterkunft",
    tabMap: "Karte",
    tabAttractions: "Sehenswürdigkeiten",
    tabFood: "Essen",
    overviewHeader: "Übersicht",
    bestTime: "Beste Reisezeit",
    currency: "Währung",
    historyHeader: "Historischer Überblick",
    routesHeader: "Reiseoptionen",
    from: "Von",
    viewMap: "Routenkarte anzeigen",
    travelTipTitle: "Reisetipp",
    travelTipText: "Preise und Dauer sind Schätzungen. Prüfen Sie immer die Echtzeit-Verfügbarkeit.",
    hotelsHeader: "Übernachtungsmöglichkeiten",
    bookRoom: "Verfügbarkeit prüfen",
    budgetStays: "Budget & Preiswert",
    luxuryStays: "Premium & Luxus",
    priceFilterLabel: "Max. Preis / Nacht",
    mapHeader: "Interaktive Karte",
    mapSubtext: "Erkunden Sie die Route, Sehenswürdigkeiten und Fotospots.",
    attractionsHeader: "Muss-man-gesehen-haben",
    allAttractions: "Alle Attraktionen",
    cameraSpots: "Fotospots",
    proTip: "Profi-Tipp",
    cuisineHeader: "Lokale Küche",
    tryAt: "Probieren bei",
    tipsHeader: "Wichtige Reisetipps",
    settingsHeader: "Einstellungen",
    languageLabel: "Sprache",
    typographyLabel: "Typografie",
    fontStandard: "Standard",
    fontModern: "Modern",
    fontClassic: "Klassisch",
    fontEditorial: "Redaktionell"
  },
  it: {
    heroTitle: "Scopri la Tua Prossima",
    heroSubtitle: "La tua guida intelligente per storia, percorsi, luoghi nascosti e delizie culinaires.",
    fromPlaceholder: "Da (Origine)",
    toPlaceholder: "A (Destinazione)",
    exploreButton: "Esplora",
    locating: "Localizzazione...",
    tabOverview: "Panoramica",
    tabJourney: "Viaggio",
    tabHotels: "Soggiorno",
    tabMap: "Mappa",
    tabAttractions: "Attrazioni",
    tabFood: "Cibo",
    overviewHeader: "Panoramica",
    bestTime: "Periodo Migliore",
    currency: "Valuta",
    historyHeader: "Sintesi Storica",
    routesHeader: "Opzioni di Viaggio",
    from: "Da",
    viewMap: "Vedi Mappa",
    travelTipTitle: "Consiglio di Viaggio",
    travelTipText: "Prezzi e durate sono stime. Controlla sempre la disponibilità in tempo reale.",
    hotelsHeader: "Dove Alloggiare",
    bookRoom: "Vedi Disponibilità",
    budgetStays: "Budget & Valore",
    luxuryStays: "Premium & Lusso",
    priceFilterLabel: "Prezzo Max / Notte",
    mapHeader: "Mappa Interattiva",
    mapSubtext: "Esplora il percorso, le attrazioni e i punti fotografici.",
    attractionsHeader: "Luoghi Imperdibili",
    allAttractions: "Tutte le Attrazioni",
    cameraSpots: "Punti Fotografici",
    proTip: "Consiglio Pro",
    cuisineHeader: "Cucina Locale",
    tryAt: "Prova da",
    tipsHeader: "Consigli di Viaggio Essenziali",
    settingsHeader: "Impostazioni",
    languageLabel: "Lingua",
    typographyLabel: "Tipografia",
    fontStandard: "Standard",
    fontModern: "Moderno",
    fontClassic: "Classico",
    fontEditorial: "Editoriale"
  },
  pt: {
    heroTitle: "Descubra Sua Próxima",
    heroSubtitle: "Seu guia inteligente de história, rotas, lugares escondidos e delícias culinárias.",
    fromPlaceholder: "De (Origem)",
    toPlaceholder: "Para (Destino)",
    exploreButton: "Explorar",
    locating: "Localizando...",
    tabOverview: "Visão Geral",
    tabJourney: "Jornada",
    tabHotels: "Estadias",
    tabMap: "Mapa",
    tabAttractions: "Atrações",
    tabFood: "Comida",
    overviewHeader: "Visão Geral",
    bestTime: "Melhor Época",
    currency: "Moeda",
    historyHeader: "Resumo Histórico",
    routesHeader: "Opções de Viagem",
    from: "De",
    viewMap: "Ver Mapa",
    travelTipTitle: "Dica de Viagem",
    travelTipText: "Preços e durações são estimativas. Verifique sempre a disponibilidade real.",
    hotelsHeader: "Onde Ficar",
    bookRoom: "Ver Disponibilidade",
    budgetStays: "Econômico & Valor",
    luxuryStays: "Premium & Luxo",
    priceFilterLabel: "Preço Máx / Noite",
    mapHeader: "Mapa Interativo",
    mapSubtext: "Explore a rota, atrações e pontos fotográficos.",
    attractionsHeader: "Locais Imperdíveis",
    allAttractions: "Todas as Atrações",
    cameraSpots: "Spots de Câmera",
    proTip: "Dica Pro",
    cuisineHeader: "Culinária Local",
    tryAt: "Experimente em",
    tipsHeader: "Dicas Essenciais",
    settingsHeader: "Configurações",
    languageLabel: "Idioma",
    typographyLabel: "Tipografia",
    fontStandard: "Padrão",
    fontModern: "Moderno",
    fontClassic: "Clássico",
    fontEditorial: "Editorial"
  },
  zh: {
    heroTitle: "发现您的下一次",
    heroSubtitle: "您的历史、路线、隐秘景点和美食的智能指南。",
    fromPlaceholder: "从 (出发地)",
    toPlaceholder: "到 (目的地)",
    exploreButton: "探索",
    locating: "定位中...",
    tabOverview: "概览",
    tabJourney: "旅程",
    tabHotels: "住宿",
    tabMap: "地图",
    tabAttractions: "景点",
    tabFood: "餐饮",
    overviewHeader: "概览",
    bestTime: "最佳旅游时间",
    currency: "货币",
    historyHeader: "历史简介",
    routesHeader: "旅行选择",
    from: "从",
    viewMap: "查看路线图",
    travelTipTitle: "旅行贴士",
    travelTipText: "价格和时间仅供参考。请务必查看实时情况。",
    hotelsHeader: "住宿推荐",
    bookRoom: "查看空房",
    budgetStays: "经济实惠",
    luxuryStays: "高端豪华",
    priceFilterLabel: "最高每晚价格",
    mapHeader: "交互式地图",
    mapSubtext: "探索路线、景点和摄影点。",
    attractionsHeader: "必游景点",
    allAttractions: "所有景点",
    cameraSpots: "摄影点",
    proTip: "专业提示",
    cuisineHeader: "当地美食",
    tryAt: "尝试地点",
    tipsHeader: "重要旅行贴士",
    settingsHeader: "设置",
    languageLabel: "语言",
    typographyLabel: "字体风格",
    fontStandard: "标准",
    fontModern: "现代",
    fontClassic: "经典",
    fontEditorial: "编辑风格"
  },
  ja: {
    heroTitle: "次の冒険を発見しよう",
    heroSubtitle: "歴史、ルート、隠れた名所、そして美食のためのインテリジェントな旅行ガイド。",
    fromPlaceholder: "出発地",
    toPlaceholder: "目的地",
    exploreButton: "探索する",
    locating: "位置特定中...",
    tabOverview: "概要",
    tabJourney: "旅程",
    tabHotels: "宿泊",
    tabMap: "地図",
    tabAttractions: "観光名所",
    tabFood: "食事",
    overviewHeader: "概要",
    bestTime: "ベストシーズン",
    currency: "通貨",
    historyHeader: "歴史的概要",
    routesHeader: "移動手段",
    from: "出発",
    viewMap: "ルートマップを見る",
    travelTipTitle: "旅行のヒント",
    travelTipText: "価格と所要時間は目安です。常に最新の空き状況を確認してください。",
    hotelsHeader: "宿泊施設",
    bookRoom: "空室状況を確認",
    budgetStays: "格安＆バリュー",
    luxuryStays: "プレミアム＆ラグジュアリー",
    priceFilterLabel: "最大宿泊料金 / 泊",
    mapHeader: "インタラクティブマップ",
    mapSubtext: "ルート、観光スポット、フォトスポットを探索します。",
    attractionsHeader: "必見スポット",
    allAttractions: "すべての観光スポット",
    cameraSpots: "フォトスポット",
    proTip: "プロのヒント",
    cuisineHeader: "郷土料理",
    tryAt: "おすすめの場所",
    tipsHeader: "重要な旅行のヒント",
    settingsHeader: "設定",
    languageLabel: "言語",
    typographyLabel: "タイポグラフィ",
    fontStandard: "標準",
    fontModern: "モダン",
    fontClassic: "クラシック",
    fontEditorial: "エディトリアル"
  }
};